# Generated by Django 5.2.4 on 2026-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrition/'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
