# Generated by Django 6.0.6 on 2026-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('running_time', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=200)),
            ],
        ),
    ]
